-- Schéma VerifID (PostgreSQL). Appliqué au démarrage via spring.sql.init.mode=always.
-- Idempotent (IF NOT EXISTS) : sûr à ré-exécuter à chaque boot.

CREATE TABLE IF NOT EXISTS platforms (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(255),
    email             VARCHAR(320) NOT NULL,
    password_hash     VARCHAR(255),
    api_key           VARCHAR(255),
    otp_code          VARCHAR(32),
    otp_expiry        TIMESTAMP,
    email_verified    BOOLEAN DEFAULT FALSE,
    reset_code        VARCHAR(32),
    reset_code_expiry TIMESTAMP,
    reset_attempts    INTEGER DEFAULT 0,
    active            BOOLEAN DEFAULT TRUE,
    created_at        TIMESTAMP,
    updated_at        TIMESTAMP
);

CREATE TABLE IF NOT EXISTS verification_logs (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_id        BIGINT,
    date               TIMESTAMP,
    doc_type           VARCHAR(64),
    status             VARCHAR(32),
    reason             TEXT,
    confidence         DOUBLE PRECISION,
    processing_time_ms INTEGER,
    document_number    VARCHAR(128),
    holder_name        VARCHAR(255),
    date_of_birth      VARCHAR(32),
    issue_date         VARCHAR(32),
    expiry_date        VARCHAR(32),
    additional_fields  TEXT
);

CREATE TABLE IF NOT EXISTS super_admins (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(255),
    email             VARCHAR(320) NOT NULL,
    password_hash     VARCHAR(255),
    api_key           VARCHAR(255),
    email_verified    BOOLEAN DEFAULT TRUE,
    otp_code          VARCHAR(32),
    otp_expiry        TIMESTAMP,
    reset_code        VARCHAR(32),
    reset_code_expiry TIMESTAMP,
    reset_attempts    INTEGER DEFAULT 0,
    created_at        TIMESTAMP,
    updated_at        TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_platforms_email ON platforms(email);
CREATE INDEX IF NOT EXISTS idx_platforms_api_key ON platforms(api_key);
CREATE INDEX IF NOT EXISTS idx_verification_logs_platform ON verification_logs(platform_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_super_admins_email ON super_admins(email);
